export const CREATE_MEMBER = "CREATE_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBER_ID = "GET_MEMBER_ID";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const DELETE_MEMBER = "DELETE_MEMBER";
